version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    image: laravel-boilerplate
    container_name: laravel-boilerplate
    networks:
      - backend
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - webserver
      - mongodb
      - postgres

  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - .docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - backend

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongodb
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - backend
    working_dir: /var/lib/postgresql
    volumes:
      - .docker/database/:/var/lib/postgresql

networks:
  backend:
    driver: bridge
